/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
     "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:86b12838-c4b6-4675-a1da-ce7ab797306f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5moWvOSZ5",
    "aws_user_pools_web_client_id": "5pl946htm0o0ssiksjs08cudlu",
    "oauth": {
        "domain": "y4bnmh59o4hm-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://main.d398kv8yeh6ttc.amplifyapp.com/,http://localhost:5173/",
        "redirectSignOut": "https://main.d398kv8yeh6ttc.amplifyapp.com/,http://localhost:5173/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
